//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VATrainer.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VATrainer.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjective law.
        /// </summary>
        public static string Adjective_law {
            get {
                return ResourceManager.GetString("Adjective_law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing.
        /// </summary>
        public static string Browsing {
            get {
                return ResourceManager.GetString("Browsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse the content as you like.
        /// </summary>
        public static string Browsing_Explanation {
            get {
                return ResourceManager.GetString("Browsing_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confident.
        /// </summary>
        public static string Confident {
            get {
                return ResourceManager.GetString("Confident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption Tax.
        /// </summary>
        public static string ConsumptionTax {
            get {
                return ResourceManager.GetString("ConsumptionTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal law.
        /// </summary>
        public static string Criminal_law {
            get {
                return ResourceManager.GetString("Criminal_law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display instruction.
        /// </summary>
        public static string DisplayInstruction {
            get {
                return ResourceManager.GetString("DisplayInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show again.
        /// </summary>
        public static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU Directive.
        /// </summary>
        public static string EU_Directive {
            get {
                return ResourceManager.GetString("EU_Directive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense side.
        /// </summary>
        public static string Expense_side {
            get {
                return ResourceManager.GetString("Expense_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have fun and good luck!.
        /// </summary>
        public static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe over the flash card to switch between question and answer. Choose the Button “Confident” if you know the answer. Choose “Unconfident” if you are still uncertain. If you classify a question as confident, it moves from the left to the middle stack. If you classify the question as confident again, it moves to the right stack and you won’t be asked again..
        /// </summary>
        public static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International VAT law.
        /// </summary>
        public static string International_VAT_law {
            get {
                return ResourceManager.GetString("International_VAT_law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen: .
        /// </summary>
        public static string Last_seen___ {
            get {
                return ResourceManager.GetString("Last_seen_:_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning.
        /// </summary>
        public static string Learning {
            get {
                return ResourceManager.GetString("Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare yourself for an exam.
        /// </summary>
        public static string Learning_Explanation {
            get {
                return ResourceManager.GetString("Learning_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OECD - ROW.
        /// </summary>
        public static string OECD_ROW {
            get {
                return ResourceManager.GetString("OECD_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Reset_Question {
            get {
                return ResourceManager.GetString("Reset_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset your learning progress for the selected topic..
        /// </summary>
        public static string Reset_Text {
            get {
                return ResourceManager.GetString("Reset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue side.
        /// </summary>
        public static string Revenue_side {
            get {
                return ResourceManager.GetString("Revenue_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string Slow {
            get {
                return ResourceManager.GetString("Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxpayer.
        /// </summary>
        public static string Taxpayer {
            get {
                return ResourceManager.GetString("Taxpayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing.
        /// </summary>
        public static string Title_Browsing {
            get {
                return ResourceManager.GetString("Title_Browsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Title_Contents {
            get {
                return ResourceManager.GetString("Title_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATrainer.
        /// </summary>
        public static string Title_HomeDetail {
            get {
                return ResourceManager.GetString("Title_HomeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATrainer.
        /// </summary>
        public static string Title_HomeMain {
            get {
                return ResourceManager.GetString("Title_HomeMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Title_Mode {
            get {
                return ResourceManager.GetString("Title_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question - Answer.
        /// </summary>
        public static string Title_QA {
            get {
                return ResourceManager.GetString("Title_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Title_Resources {
            get {
                return ResourceManager.GetString("Title_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Title_Training {
            get {
                return ResourceManager.GetString("Title_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfident.
        /// </summary>
        public static string Unconfident {
            get {
                return ResourceManager.GetString("Unconfident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Added Tax.
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT and accounting.
        /// </summary>
        public static string VAT_and_accounting {
            get {
                return ResourceManager.GetString("VAT_and_accounting", resourceCulture);
            }
        }
    }
}
