//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VATrainer.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VATrainer.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing.
        /// </summary>
        public static string Browsing {
            get {
                return ResourceManager.GetString("Browsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse the content as you like.
        /// </summary>
        public static string Browsing_Explanation {
            get {
                return ResourceManager.GetString("Browsing_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption Tax.
        /// </summary>
        public static string ConsumptionTax {
            get {
                return ResourceManager.GetString("ConsumptionTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU Directive.
        /// </summary>
        public static string EU_Directive {
            get {
                return ResourceManager.GetString("EU_Directive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guided Learning.
        /// </summary>
        public static string Guided_Learning {
            get {
                return ResourceManager.GetString("Guided_Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare yourself for an exam.
        /// </summary>
        public static string Guided_Learning_Explanation {
            get {
                return ResourceManager.GetString("Guided_Learning_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OECD - ROW.
        /// </summary>
        public static string OECD_ROW {
            get {
                return ResourceManager.GetString("OECD_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing.
        /// </summary>
        public static string Title_Browsing {
            get {
                return ResourceManager.GetString("Title_Browsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Title_Contents {
            get {
                return ResourceManager.GetString("Title_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATrainer.
        /// </summary>
        public static string Title_HomeDetail {
            get {
                return ResourceManager.GetString("Title_HomeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATrainer.
        /// </summary>
        public static string Title_HomeMaster {
            get {
                return ResourceManager.GetString("Title_HomeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Title_Mode {
            get {
                return ResourceManager.GetString("Title_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question - Answer.
        /// </summary>
        public static string Title_QA {
            get {
                return ResourceManager.GetString("Title_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Title_Resources {
            get {
                return ResourceManager.GetString("Title_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Title_Training {
            get {
                return ResourceManager.GetString("Title_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Added Tax.
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
    }
}
